### ISSUE TITLE
Maximize and Minimize buttons are the wrong colors

### ISSUE THREAD

**Issue by INFORMATION89** [Dinno-DEV/zen-minimal-exit-menu#11]
Maximize is meant to be green and minimize yellow

![Image](https://github.com/user-attachments/assets/92408ebf-052a-4415-8773-d71abd29e30e)

<img width="80" alt="Image" src="https://github.com/user-attachments/assets/65c260f7-5a68-422a-a94c-6b179ca5f31d" />

**Comment by berkaykrc** [comment]
```css
titlebar-min {
      background-color: hsl(60, 50%, 50%) !important;
  }
  
  .titlebar-max, .titlebar-restore {
      background-color: hsl(130, 50%, 40%) !important;
  }
  
  .titlebar-close {
      background-color: hsl(0, 50%, 50%) !important;
```
